// Render a `.d.ts` sidecar that augments `PromptFileRegistry` for a single
// prompt source file. Pure: produces a string + target path, never touches
// disk. The orchestrator (`run-codegen.ts`) decides when to write.

import type { Path } from '../services/index.ts'
import { path } from '../services/index.ts'
import type { ExtractedVars } from './extract-placeholders.ts'

export interface SidecarOutput {
  /** Absolute path where the sidecar should be written. */
  readonly targetPath: Path
  /** Full file contents (LF line endings, trailing newline). */
  readonly content: string
  /** The `'@/...'` registry key this sidecar declares. Useful for diagnostics. */
  readonly registryKey: string
}

/**
 * Build a single sidecar for `sourcePath`. The registry key is `'@/'` plus the
 * path relative to `projectRoot`, using forward slashes — matching what
 * `step.define({ promptFile: '@/...' })` will look up at the type level.
 *
 * Files with no placeholders still produce a sidecar so a `step.define` call
 * site that points at them enforces "no vars allowed" (rather than silently
 * widening to `PromptVars`).
 */
export function emitSidecar(
  sourcePath: Path,
  projectRoot: Path,
  vars: ExtractedVars,
): SidecarOutput {
  // Defense-in-depth against codegen self-amplification: a `.d.ts` source
  // would produce a `.d.ts.d.ts` sidecar that the next codegen pass would
  // pick up again and so on. `runCodegen` filters discovery results, but
  // anyone calling `emitSidecar` directly (or with a custom discovery layer)
  // gets the same protection here.
  if (sourcePath.endsWith('.d.ts')) {
    throw new Error(
      `emitSidecar: refusing to emit sidecar for a path ending in .d.ts: ${sourcePath}`,
    )
  }
  const relative = sourceRelativeKey(sourcePath, projectRoot)
  // POSIX filenames may contain newlines, which would break out of the
  // `// Source: ${relative}` line comment and let attacker-controlled bytes
  // inject TypeScript declarations into the emitted `.d.ts`. Newline-in-
  // filename is virtually always a mistake, so reject early with a clear
  // message rather than escaping silently.
  if (/[\r\n]/.test(relative)) {
    throw new Error(
      `emitSidecar: refusing to emit sidecar for source path containing newline characters: ${JSON.stringify(relative)}`,
    )
  }
  const registryKey = `@/${relative}`
  const shape = renderVarsShape(vars)
  const content =
    `// AUTO-GENERATED by \`orch types\` — do not edit.\n` +
    `// Source: ${relative}\n` +
    `declare module 'orch' {\n` +
    `  interface PromptFileRegistry {\n` +
    `    ${JSON.stringify(registryKey)}: ${shape}\n` +
    `  }\n` +
    `}\n` +
    `export {}\n`
  return { targetPath: path(`${sourcePath}.d.ts`), content, registryKey }
}

function renderVarsShape(vars: ExtractedVars): string {
  if (vars.required.length === 0 && vars.optional.length === 0) {
    // `Record<string, never>` rejects extra keys at the call site, so a
    // `promptFile:` with no placeholders surfaces an error if a caller
    // passes `vars`. Matches `VarsOf<'static'>` from the TLT extractor.
    return 'Record<string, never>'
  }
  const required = vars.required.map((name) => `${quoteKey(name)}: string | number | boolean`)
  const optional = vars.optional.map((name) => `${quoteKey(name)}?: string | number | boolean`)
  const fields = [...required, ...optional].join('; ')
  return `{ ${fields} }`
}

/**
 * Quote a key if it isn't a bare identifier so a placeholder like `{{user-id}}`
 * still produces a valid `.d.ts`. The runtime placeholder regex only allows
 * `[a-zA-Z_][a-zA-Z0-9_]*`, so under current rules every key is bare — the
 * quoter is defensive and would only matter if the placeholder grammar widens
 * later.
 */
function quoteKey(name: string): string {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name) ? name : JSON.stringify(name)
}

function sourceRelativeKey(sourcePath: Path, projectRoot: Path): string {
  if (sourcePath === projectRoot) return ''
  const prefix = `${projectRoot}/`
  if (sourcePath.startsWith(prefix)) return sourcePath.slice(prefix.length)
  // Source lives outside the project root — fall back to the absolute path.
  // This is unusual (users almost always point `include` at paths inside the
  // repo) but emitting *something* keeps codegen well-defined.
  return sourcePath
}
